//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch_Report
    {
        public int ID { get; set; }
        public int Material_ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Volume { get; set; }
        public Nullable<double> Actual_Volume { get; set; }
        public double Reserved_Volume { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
