//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID { get; set; }
        public int Number { get; set; }
        public int Contract_Type_ID { get; set; }
        public int Employee_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
        public Nullable<int> Supplier_ID { get; set; }
        public int Contract_Subject_ID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime Date_Start { get; set; }
        public System.DateTime Date_End { get; set; }
        public int Status_ID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Contract_Types Contract_Types { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Equipments Equipments { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
