//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Contract = new HashSet<Contract>();
        }
        
        [Required]
        public int ID { get; set; }
        [Required(ErrorMessage = "Необходимо указать имя сотрудника")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Необходимо указать фамилию сотрудника")]
        public string Surname { get; set; }

        public string Patronymic { get; set; }
        [Required(ErrorMessage = "Необходимо указать идентификатор должности сотрудника")]
        public int Position_ID { get; set; }
        [Required(ErrorMessage = "Необходимо указать идентификатор отдела сотрудника")]
        public int Department_ID { get; set; }
        [Required(ErrorMessage = "Необходимо указать дату найма сотрудника")]
        public System.DateTime Hire_Date { get; set; }
        [Required(ErrorMessage = "Необходимо указать заработную плату сотрудника")]
        public decimal Salary { get; set; }
        [Required]
        public Nullable<int> Authorisation_ID { get; set; }
    
        public virtual Authorisation Authorisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Position Position { get; set; }
    }
}
