//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorisation> Authorisation { get; set; }
        public virtual DbSet<Batch_Report> Batch_Report { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Contract_Types> Contract_Types { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipment_Types> Equipment_Types { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<Markets> Markets { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Supplier_Types> Supplier_Types { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
    }
}
